/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BreadCrumb: typeof import('./src/components/BreadCrumb.vue')['default']
    CloudHeader: typeof import('./src/components/CloudHeader.vue')['default']
    ContextMenu: typeof import('./src/components/ContextMenu.vue')['default']
    DefaultPreview: typeof import('./src/components/preview/DefaultPreview.vue')['default']
    DefaultPreviewer: typeof import('./src/components/preview/DefaultPreviewer.vue')['default']
    DropDown: typeof import('./src/components/DropDown.vue')['default']
    FileBox: typeof import('./src/components/FileBox.vue')['default']
    FileLine: typeof import('./src/components/FileLine.vue')['default']
    FilePreviewer: typeof import('./src/components/FilePreviewer.vue')['default']
    FileRecord: typeof import('./src/components/FileRecord.vue')['default']
    FileRecordList: typeof import('./src/components/FileRecordList.vue')['default']
    FileShareList: typeof import('./src/components/FileShareList.vue')['default']
    FileSystem: typeof import('./src/components/FileSystem.vue')['default']
    FileTable: typeof import('./src/components/FileTable.vue')['default']
    FileTree: typeof import('./src/components/FileTree.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    MenuBar: typeof import('./src/components/MenuBar.vue')['default']
    NavBox: typeof import('./src/components/NavBox.vue')['default']
    Notifacation: typeof import('./src/components/Notifacation.vue')['default']
    Notification: typeof import('./src/components/Notification.vue')['default']
    PageSelector: typeof import('./src/components/PageSelector.vue')['default']
    PDFPreview: typeof import('./src/components/preview/PDFPreview.vue')['default']
    ProgressBar: typeof import('./src/components/ProgressBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShareDetails: typeof import('./src/components/ShareDetails.vue')['default']
  }
}
